package com.rachierudragos.dotatracker.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.rachierudragos.dotatracker.database.Ability;

import com.rachierudragos.dotatracker.database.AbilityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig abilityDaoConfig;

    private final AbilityDao abilityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        abilityDaoConfig = daoConfigMap.get(AbilityDao.class).clone();
        abilityDaoConfig.initIdentityScope(type);

        abilityDao = new AbilityDao(abilityDaoConfig, this);

        registerDao(Ability.class, abilityDao);
    }
    
    public void clear() {
        abilityDaoConfig.clearIdentityScope();
    }

    public AbilityDao getAbilityDao() {
        return abilityDao;
    }

}
